### Answer 1: Create a new notebook for this task. Be sure to import the relevant libraries, along with your ords_prods_merge dataframe

In [1]:
# Import the Python libraries
import pandas as pd
import numpy as np
import os

### Import the dataset orders_products_merge_0120.pkl to a dataframe

In [2]:
# Create a path variable
path = r'C:\Users\sands\Documents\01-2022 Instacart Basket Analysis'

In [3]:
#Import the pickle file
ords_prods_merge  = pd.read_pickle(os.path.join(path,'02 Data','Prepared Data','orders_products_merge_0120.pkl'))

In [4]:
# Check the shape of the dataframe
ords_prods_merge.shape

(32404859, 19)

In [5]:
# Check the columns and first few rows
ords_prods_merge.head(20)

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0,product_name,aisle_id,department_id,prices,_merge,prices_range_loc,busiest days,busiest_period_of_day
0,2539329,1,prior,1,2,8,NaN,196,1,0,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average Orders
1,2398795,1,prior,2,3,7,15.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Least busy,Average Orders
2,473747,1,prior,3,3,12,21.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Least busy,Most Orders
3,2254736,1,prior,4,4,7,29.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Least busy,Average Orders
4,431534,1,prior,5,4,15,28.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Least busy,Most Orders
5,3367565,1,prior,6,2,7,19.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average Orders
6,550135,1,prior,7,1,9,20.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Busiest day,Most Orders
7,3108588,1,prior,8,1,14,14.0,196,2,1,195,Soda,77,7,9.0,both,Mid-range product,Busiest day,Most Orders
8,2295261,1,prior,9,1,16,0.0,196,4,1,195,Soda,77,7,9.0,both,Mid-range product,Busiest day,Most Orders
9,2550362,1,prior,10,4,8,30.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Least busy,Average Orders
10,2968173,15,prior,15,1,9,7.0,196,2,0,195,Soda,77,7,9.0,both,Mid-range product,Busiest day,Most Orders
11,1870022,15,prior,17,2,16,8.0,196,6,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most Orders
12,1911383,15,prior,18,2,11,7.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most Orders
13,2715276,15,prior,21,1,9,7.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Busiest day,Most Orders
14,487368,15,prior,22,1,10,14.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Busiest day,Most Orders
15,2293453,19,prior,2,5,14,6.0,196,3,0,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most Orders
16,1973799,19,prior,5,6,12,8.0,196,15,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most Orders
17,532817,19,prior,7,4,17,6.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Least busy,Average Orders
18,1573906,21,prior,10,3,10,6.0,196,2,0,195,Soda,77,7,9.0,both,Mid-range product,Least busy,Most Orders
19,1593000,31,prior,10,3,8,7.0,196,17,0,195,Soda,77,7,9.0,both,Mid-range product,Least busy,Average Orders

### Answer 2: Find the aggregated mean of the “order_number” column grouped by “department_id”  for the entire dataframe

In [6]:
# Group the dataset by department_id and find the aggregated mean of the order_number column
ords_prods_merge.groupby('department_id').agg({'order_number':['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

### Answer 3: How do the results for the entire dataframe differ from those of the subset?

1. Running the aggregate function on the entire dataset yielded all the department_ids instead of just 8
2. The mean for a few depatment_ids like 4, 20 is lower when looking at the whole dataset but for some it remains same
3. The department id 21 has the highest order number mean

### Answer 4: Follow the instructions in the Exercise for creating a loyalty flag for existing customers using the transform() and loc() functions.

In [7]:
# Create max order column
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [8]:
# Check the dataframe for the new max_order column
ords_prods_merge.head(15)

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0,product_name,aisle_id,department_id,prices,_merge,prices_range_loc,busiest days,busiest_period_of_day,max_order
0,2539329,1,prior,1,2,8,NaN,196,1,0,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average Orders,10
1,2398795,1,prior,2,3,7,15.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Least busy,Average Orders,10
2,473747,1,prior,3,3,12,21.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Least busy,Most Orders,10
3,2254736,1,prior,4,4,7,29.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Least busy,Average Orders,10
4,431534,1,prior,5,4,15,28.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Least busy,Most Orders,10
5,3367565,1,prior,6,2,7,19.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Average Orders,10
6,550135,1,prior,7,1,9,20.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Busiest day,Most Orders,10
7,3108588,1,prior,8,1,14,14.0,196,2,1,195,Soda,77,7,9.0,both,Mid-range product,Busiest day,Most Orders,10
8,2295261,1,prior,9,1,16,0.0,196,4,1,195,Soda,77,7,9.0,both,Mid-range product,Busiest day,Most Orders,10
9,2550362,1,prior,10,4,8,30.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Least busy,Average Orders,10
10,2968173,15,prior,15,1,9,7.0,196,2,0,195,Soda,77,7,9.0,both,Mid-range product,Busiest day,Most Orders,22
11,1870022,15,prior,17,2,16,8.0,196,6,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most Orders,22
12,1911383,15,prior,18,2,11,7.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Most Orders,22
13,2715276,15,prior,21,1,9,7.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Busiest day,Most Orders,22
14,487368,15,prior,22,1,10,14.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Busiest day,Most Orders,22

In [9]:
# Assign a flag based on the number of orders to each customer
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal Customer'
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular Customer'
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New Customer'

In [10]:
# Check the fequency of different loyalty flags
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

Regular Customer    15876776
Loyal Customer      10284093
New Customer         6243990
Name: loyalty_flag, dtype: int64

In [11]:
# Check the relevant columns of the first few rows
ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New Customer             1
1         1      New Customer             2
2         1      New Customer             3
3         1      New Customer             4
4         1      New Customer             5
5         1      New Customer             6
6         1      New Customer             7
7         1      New Customer             8
8         1      New Customer             9
9         1      New Customer            10
10       15  Regular Customer            15
11       15  Regular Customer            17
12       15  Regular Customer            18
13       15  Regular Customer            21
14       15  Regular Customer            22
15       19      New Customer             2
16       19      New Customer             5
17       19      New Customer             7
18       21  Regular Customer            10
19       31  Regular Customer            10
20       31  Regular Customer            17
21       43  Regular Customer             6
22       43  Regular Customer             9
23       52  Regular Customer             1
24       52  Regular Customer             2
25       52  Regular Customer             3
26       52  Regular Customer             5
27       52  Regular Customer             7
28       52  Regular Customer             9
29       52  Regular Customer            10
30       52  Regular Customer            11
31       52  Regular Customer            12
32       52  Regular Customer            15
33       52  Regular Customer            17
34       52  Regular Customer            18
35       52  Regular Customer            19
36       52  Regular Customer            21
37       67  Regular Customer             1
38       67  Regular Customer             2
39       67  Regular Customer             3
40       67  Regular Customer             4
41       67  Regular Customer             5
42       67  Regular Customer             6
43       67  Regular Customer             8
44       67  Regular Customer             9
45       67  Regular Customer            10
46       67  Regular Customer            11
47       67  Regular Customer            12
48       67  Regular Customer            13
49       67  Regular Customer            14
50       67  Regular Customer            16
51       67  Regular Customer            18
52       67  Regular Customer            19
53       67  Regular Customer            21
54       67  Regular Customer            22
55       67  Regular Customer            23
56       81      New Customer             3
57       81      New Customer             5
58       82  Regular Customer             1
59       82  Regular Customer             3

### Answer 5: The marketing team at Instacart wants to know whether there’s a difference between the spending habits of the three types of customers you identified. Use the loyalty flag you created and check the basic statistics of the product prices for each loyalty category (Loyal Customer, Regular Customer, and New Customer). What you’re trying to determine is whether the prices of products purchased by loyal customers differ from those purchased by regular or new customers

In [13]:
# Performing Multiple Aggregations
ords_prods_merge.groupby('loyalty_flag').agg({'prices':['mean','max','min']})

                     prices
                       mean      max  min
loyalty_flag
Loyal Customer    10.386336  99999.0  1.0
New Customer      13.294670  99999.0  1.0
Regular Customer  12.495717  99999.0  1.0

From the statistics it appears that the regular customers on an average buy higher price items and the loyal customers buy the lowest priced items. It is possible that the loyal customers use instacart to buy their daily needs which are not necessarily priced high but the new customers seem to be ordering pricier items which may be something they can't find in stores.

### Answer 6: The team now wants to target different types of spenders in their marketing campaigns. This can be achieved by looking at the prices of the items people are buying. Create a spending flag for each user based on the average price across all their orders using the following criteria:

##### o	If the mean of the prices of products purchased by a user is lower than 10, then flag them as a “Low spender.”
##### o	If the mean of the prices of products purchased by a user is higher than or equal to 10, then flag them as a “High spender.”

In [14]:
# Create mean price column
ords_prods_merge['mean_price'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [16]:
# Check the dataframe for the new mean_price column
ords_prods_merge.head(15)

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,aisle_id,department_id,prices,_merge,prices_range_loc,busiest days,busiest_period_of_day,max_order,loyalty_flag,mean_price
0,2539329,1,prior,1,2,8,NaN,196,1,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Average Orders,10,New Customer,6.367797
1,2398795,1,prior,2,3,7,15.0,196,1,1,...,77,7,9.0,both,Mid-range product,Least busy,Average Orders,10,New Customer,6.367797
2,473747,1,prior,3,3,12,21.0,196,1,1,...,77,7,9.0,both,Mid-range product,Least busy,Most Orders,10,New Customer,6.367797
3,2254736,1,prior,4,4,7,29.0,196,1,1,...,77,7,9.0,both,Mid-range product,Least busy,Average Orders,10,New Customer,6.367797
4,431534,1,prior,5,4,15,28.0,196,1,1,...,77,7,9.0,both,Mid-range product,Least busy,Most Orders,10,New Customer,6.367797
5,3367565,1,prior,6,2,7,19.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Average Orders,10,New Customer,6.367797
6,550135,1,prior,7,1,9,20.0,196,1,1,...,77,7,9.0,both,Mid-range product,Busiest day,Most Orders,10,New Customer,6.367797
7,3108588,1,prior,8,1,14,14.0,196,2,1,...,77,7,9.0,both,Mid-range product,Busiest day,Most Orders,10,New Customer,6.367797
8,2295261,1,prior,9,1,16,0.0,196,4,1,...,77,7,9.0,both,Mid-range product,Busiest day,Most Orders,10,New Customer,6.367797
9,2550362,1,prior,10,4,8,30.0,196,1,1,...,77,7,9.0,both,Mid-range product,Least busy,Average Orders,10,New Customer,6.367797
10,2968173,15,prior,15,1,9,7.0,196,2,0,...,77,7,9.0,both,Mid-range product,Busiest day,Most Orders,22,Regular Customer,3.980556
11,1870022,15,prior,17,2,16,8.0,196,6,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Most Orders,22,Regular Customer,3.980556
12,1911383,15,prior,18,2,11,7.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Most Orders,22,Regular Customer,3.980556
13,2715276,15,prior,21,1,9,7.0,196,1,1,...,77,7,9.0,both,Mid-range product,Busiest day,Most Orders,22,Regular Customer,3.980556
14,487368,15,prior,22,1,10,14.0,196,1,1,...,77,7,9.0,both,Mid-range product,Busiest day,Most Orders,22,Regular Customer,3.980556

In [17]:
# Assign a flag based on the number of orders to each customer
ords_prods_merge.loc[ords_prods_merge['mean_price'] >= 10, 'spending_flag'] = 'High Spender'
ords_prods_merge.loc[ords_prods_merge['mean_price'] < 10, 'spending_flag'] = 'Low Spender'

In [18]:
# Check the fequency of the two spending flags
ords_prods_merge['spending_flag'].value_counts(dropna = False)

Low Spender     31770614
High Spender      634245
Name: spending_flag, dtype: int64

### Answer 7:	In order to send relevant notifications to users within the app (for instance, asking users if they want to buy the same item again), the Instacart team wants you to determine frequent versus non-frequent customers. Create an order frequency flag that marks the regularity of a user’s ordering behavior according to the median in the “days_since_prior_order” column. The criteria for the flag should be as follows:
#### o	If the median of “days_since_prior_order” is higher than 20, then the customer should be labeled a “Non-frequent customer.”
#### o	If the median is higher than 10 and lower than or equal to 20, then the customer should be labeled a “Regular customer.”
#### o	If the median is lower than or equal to 10, then the customer should be labeled a “Frequent customer.”

In [19]:
# Create median_order_period column
ords_prods_merge['median_order_period'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [26]:
# Check the dataframe for the new median_order_period column
ords_prods_merge.head(60)

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,_merge,prices_range_loc,busiest days,busiest_period_of_day,max_order,loyalty_flag,mean_price,spending_flag,median_order_period,order_frequency_flag
0,2539329,1,prior,1,2,8,NaN,196,1,0,...,both,Mid-range product,Regularly busy,Average Orders,10,New Customer,6.367797,Low Spender,20.5,Non-frequent customer
1,2398795,1,prior,2,3,7,15.0,196,1,1,...,both,Mid-range product,Least busy,Average Orders,10,New Customer,6.367797,Low Spender,20.5,Non-frequent customer
2,473747,1,prior,3,3,12,21.0,196,1,1,...,both,Mid-range product,Least busy,Most Orders,10,New Customer,6.367797,Low Spender,20.5,Non-frequent customer
3,2254736,1,prior,4,4,7,29.0,196,1,1,...,both,Mid-range product,Least busy,Average Orders,10,New Customer,6.367797,Low Spender,20.5,Non-frequent customer
4,431534,1,prior,5,4,15,28.0,196,1,1,...,both,Mid-range product,Least busy,Most Orders,10,New Customer,6.367797,Low Spender,20.5,Non-frequent customer
5,3367565,1,prior,6,2,7,19.0,196,1,1,...,both,Mid-range product,Regularly busy,Average Orders,10,New Customer,6.367797,Low Spender,20.5,Non-frequent customer
6,550135,1,prior,7,1,9,20.0,196,1,1,...,both,Mid-range product,Busiest day,Most Orders,10,New Customer,6.367797,Low Spender,20.5,Non-frequent customer
7,3108588,1,prior,8,1,14,14.0,196,2,1,...,both,Mid-range product,Busiest day,Most Orders,10,New Customer,6.367797,Low Spender,20.5,Non-frequent customer
8,2295261,1,prior,9,1,16,0.0,196,4,1,...,both,Mid-range product,Busiest day,Most Orders,10,New Customer,6.367797,Low Spender,20.5,Non-frequent customer
9,2550362,1,prior,10,4,8,30.0,196,1,1,...,both,Mid-range product,Least busy,Average Orders,10,New Customer,6.367797,Low Spender,20.5,Non-frequent customer
10,2968173,15,prior,15,1,9,7.0,196,2,0,...,both,Mid-range product,Busiest day,Most Orders,22,Regular Customer,3.980556,Low Spender,10.0,Frequent customer
11,1870022,15,prior,17,2,16,8.0,196,6,1,...,both,Mid-range product,Regularly busy,Most Orders,22,Regular Customer,3.980556,Low Spender,10.0,Frequent customer
12,1911383,15,prior,18,2,11,7.0,196,1,1,...,both,Mid-range product,Regularly busy,Most Orders,22,Regular Customer,3.980556,Low Spender,10.0,Frequent customer
13,2715276,15,prior,21,1,9,7.0,196,1,1,...,both,Mid-range product,Busiest day,Most Orders,22,Regular Customer,3.980556,Low Spender,10.0,Frequent customer
14,487368,15,prior,22,1,10,14.0,196,1,1,...,both,Mid-range product,Busiest day,Most Orders,22,Regular Customer,3.980556,Low Spender,10.0,Frequent customer
15,2293453,19,prior,2,5,14,6.0,196,3,0,...,both,Mid-range product,Regularly busy,Most Orders,9,New Customer,8.372059,Low Spender,6.0,Frequent customer
16,1973799,19,prior,5,6,12,8.0,196,15,1,...,both,Mid-range product,Regularly busy,Most Orders,9,New Customer,8.372059,Low Spender,6.0,Frequent customer
17,532817,19,prior,7,4,17,6.0,196,1,1,...,both,Mid-range product,Least busy,Average Orders,9,New Customer,8.372059,Low Spender,6.0,Frequent customer
18,1573906,21,prior,10,3,10,6.0,196,2,0,...,both,Mid-range product,Least busy,Most Orders,33,Regular Customer,7.012683,Low Spender,7.5,Frequent customer
19,1593000,31,prior,10,3,8,7.0,196,17,0,...,both,Mid-range product,Least busy,Average Orders,20,Regular Customer,8.137793,Low Spender,6.0,Frequent customer
20,2231262,31,prior,17,3,11,8.0,196,14,1,...,both,Mid-range product,Least busy,Most Orders,20,Regular Customer,8.137793,Low Spender,6.0,Frequent customer
21,2580647,43,prior,6,4,16,4.0,196,9,0,...,both,Mid-range product,Least busy,Most Orders,11,Regular Customer,7.444898,Low Spender,10.0,Frequent customer
22,2187180,43,prior,9,4,12,3.0,196,1,1,...,both,Mid-range product,Least busy,Most Orders,11,Regular Customer,7.444898,Low Spender,10.0,Frequent customer
23,2497897,52,prior,1,1,9,NaN,196,4,0,...,both,Mid-range product,Busiest day,Most Orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent customer
24,1318871,52,prior,2,1,10,7.0,196,5,1,...,both,Mid-range product,Busiest day,Most Orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent customer
25,1261384,52,prior,3,1,10,7.0,196,3,1,...,both,Mid-range product,Busiest day,Most Orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent customer
26,580568,52,prior,5,2,10,8.0,196,6,1,...,both,Mid-range product,Regularly busy,Most Orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent customer
27,2428073,52,prior,7,2,7,8.0,196,5,1,...,both,Mid-range product,Regularly busy,Average Orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent customer
28,342306,52,prior,9,1,11,7.0,196,5,1,...,both,Mid-range product,Busiest day,Most Orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent customer
29,1520353,52,prior,10,2,10,8.0,196,4,1,...,both,Mid-range product,Regularly busy,Most Orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent customer
30,2542086,52,prior,11,2,9,7.0,196,3,1,...,both,Mid-range product,Regularly busy,Most Orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent customer
31,944694,52,prior,12,1,16,6.0,196,7,1,...,both,Mid-range product,Busiest day,Most Orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent customer
32,1268191,52,prior,15,2,11,8.0,196,3,1,...,both,Mid-range product,Regularly busy,Most Orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent customer
33,1122089,52,prior,17,2,10,6.0,196,4,1,...,both,Mid-range product,Regularly busy,Most Orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent customer
34,1498922,52,prior,18,2,10,14.0,196,6,1,...,both,Mid-range product,Regularly busy,Most Orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent customer
35,180919,52,prior,19,3,8,8.0,196,4,1,...,both,Mid-range product,Least busy,Average Orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent customer
36,2695875,52,prior,21,5,10,30.0,196,1,1,...,both,Mid-range product,Regularly busy,Most Orders,27,Regular Customer,6.356287,Low Spender,8.0,Frequent customer
37,3205960,67,prior,1,3,11,NaN,196,1,0,...,both,Mid-range product,Least busy,Most Orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent customer
38,970922,67,prior,2,1,15,5.0,196,2,1,...,both,Mid-range product,Busiest day,Most Orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent customer
39,596585,67,prior,3,1,13,7.0,196,2,1,...,both,Mid-range product,Busiest day,Most Orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent customer
40,2037087,67,prior,4,2,9,8.0,196,1,1,...,both,Mid-range product,Regularly busy,Most Orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent customer
41,2474111,67,prior,5,3,14,8.0,196,2,1,...,both,Mid-range product,Least busy,Most Orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent customer
42,1568481,67,prior,6,3,12,7.0,196,2,1,...,both,Mid-range product,Least busy,Most Orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent customer
43,2048527,67,prior,8,2,11,7.0,196,1,1,...,both,Mid-range product,Regularly busy,Most Orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent customer
44,2389031,67,prior,9,2,14,7.0,196,1,1,...,both,Mid-range product,Regularly busy,Most Orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent customer
45,2378562,67,prior,10,1,10,6.0,196,1,1,...,both,Mid-range product,Busiest day,Most Orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent customer
46,1515698,67,prior,11,1,11,7.0,196,1,1,...,both,Mid-range product,Busiest day,Most Orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent customer
47,1928050,67,prior,12,2,12,8.0,196,1,1,...,both,Mid-range product,Regularly busy,Most Orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent customer
48,1949274,67,prior,13,1,10,6.0,196,1,1,...,both,Mid-range product,Busiest day,Most Orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent customer
49,551869,67,prior,14,1,9,7.0,196,1,1,...,both,Mid-range product,Busiest day,Most Orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent customer
50,768572,67,prior,16,4,10,9.0,196,1,1,...,both,Mid-range product,Least busy,Most Orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent customer
51,150528,67,prior,18,5,16,4.0,196,1,1,...,both,Mid-range product,Regularly busy,Most Orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent customer
52,29758,67,prior,19,0,14,9.0,196,2,1,...,both,Mid-range product,Busiest day,Most Orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent customer
53,1558976,67,prior,21,1,9,5.0,196,2,1,...,both,Mid-range product,Busiest day,Most Orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent customer
54,863974,67,prior,22,1,11,14.0,196,3,1,...,both,Mid-range product,Busiest day,Most Orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent customer
55,2308399,67,prior,23,1,14,14.0,196,1,1,...,both,Mid-range product,Busiest day,Most Orders,24,Regular Customer,7.656790,Low Spender,7.0,Frequent customer
56,2759128,81,prior,3,1,9,14.0,196,2,0,...,both,Mid-range product,Busiest day,Most Orders,7,New Customer,8.165385,Low Spender,30.0,Non-frequent customer
57,1812985,81,prior,5,2,20,30.0,196,1,1,...,both,Mid-range product,Regularly busy,Average Orders,7,New Customer,8.165385,Low Spender,30.0,Non-frequent customer
58,1889835,82,prior,1,3,15,NaN,196,6,0,...,both,Mid-range product,Least busy,Most Orders,19,Regular Customer,6.441221,Low Spender,11.5,Regular Customer
59,499460,82,prior,3,5,10,5.0,196,2,1,...,both,Mid-range product,Regularly busy,Most Orders,19,Regular Customer,6.441221,Low Spender,11.5,Regular Customer

In [22]:
# Assign a flag based on the frequency of ordering
ords_prods_merge.loc[ords_prods_merge['median_order_period'] > 20, 'order_frequency_flag'] = 'Non-frequent customer'
ords_prods_merge.loc[(ords_prods_merge['median_order_period'] <= 20) & (ords_prods_merge['median_order_period'] > 10), 'order_frequency_flag'] = 'Regular Customer'
ords_prods_merge.loc[ords_prods_merge['median_order_period'] <= 10, 'order_frequency_flag'] = 'Frequent customer'

In [24]:
# Check the fequency of the frequency flags
ords_prods_merge['order_frequency_flag'].value_counts(dropna = False)

Frequent customer        21559853
Regular Customer          7208564
Non-frequent customer     3636437
NaN                             5
Name: order_frequency_flag, dtype: int64

### Answer 9: Export your dataframe as a pickle file and store it correctly in your “Prepared Data” folder.

In [30]:
ords_prods_merge.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'ords_prods_merge0124.pkl'))